name: CI

on:
  push:
    #branches:
    #  - master
  pull_request:
    #branches:
    #  - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
      - name: Get Packages
        uses: mstksg/get-package@v1
        with:
          brew: autoconf automake libtool
          apt-get: autoconf automake libtool

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Stack
        uses: mstksg/setup-stack@v1

      - name: Cache libsecp256k1
        id: cache-libsecp256k1
        uses: actions/cache@v1
        with:
          path: .local/lib/libsecp256k1.a
          key: ${{ runner.os }}-libsecp256k1

      - name: Build libsecp256k1
        if: steps.cache-libsecp256k1.outputs.cache-hit != 'true'
        run: .github/scripts/install-libsecp256k1.sh

      - name: Build
        run: |
          true
#  tests:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os:
#          - ubuntu-latest
#        solc:
#          - 0.4.25
#          - 0.5.10
